import {chapterEntryURL} from '../ui/chapter-entry.js';
import {maryPaper} from '../ui/mary-stationery.js';
import {setPixelPrompt} from '../ui/pixel-prompts.js';
import {inspectionSpots,inspectionDialogue,menuPrices,drawMenu,drawShopCard,drawLedger} from './objects.js';
import {drawStreetSigns} from './signs.js';
import {normalizeAlexandria,alexAction} from './state.js';
import {earlyLeaveText,dialogue,interlude,place,isThought,isInterjection,isInspection,porterTopics} from './content.js';
import {SCROLL_SCALE,drawActor} from '../voyage/scale.js';
import {walkFrame} from '../voyage/motion.js';
export class Alexandria {
 constructor(v){this.v=v;this.images={};this.ready=false;this.loading=null;this.fade=null;this.menu=null;this.selected=0;this.bagOpen=false;this.distance=0;this.lastSave=0;this.approach=null;this.porterDistance=0;
 const el=document.createElement('div');el.className='alex-ui';el.hidden=true;el.innerHTML=`<button class="alex-portrait" aria-label="询问托普修斯 R"><img src="assets/malta/topsius-portrait.png" alt="托普修斯"><kbd>R</kbd></button><section class="alex-talk" role="dialog" aria-label="交谈" hidden><small></small><p></p><div class="alex-stationery" hidden></div><div class="alex-price-list" hidden></div><button data-next>继续 <kbd aria-label="空格键">␣</kbd></button><button data-close aria-label="暂离对话">× <kbd>Esc</kbd></button></section><section class="alex-menu" role="dialog" aria-label="选择去向" hidden><h2></h2><div></div><footer>W / S 选择 · ␣ 空格确认 · Esc 返回</footer></section><button class="alex-parcel-notice" hidden>已收到褐纸包裹 · <span class="desktop-instruction">按 Tab </span>查看背包</button><div class="alex-black" hidden><p></p><button data-black>继续 <kbd aria-label="空格键">␣</kbd></button></div>`;v.el.append(el);this.el=el;this.q=s=>el.querySelector(s);this.q('.alex-parcel-notice').onclick=()=>this.bag();this.q('[data-next]').onclick=()=>this.next();this.q('[data-close]').onclick=()=>this.close();this.q('[data-black]').onclick=()=>this.next();this.q('.alex-portrait').onclick=()=>this.talk(this.a.stage<2?'scholarBefore':'scholar');this.suspended=false;
 }
 get a(){return this.v.s.alexandria;}
 save(){this.v.persist();}
 async enter(){const v=this.v;v.auto=null;v.dialogue=null;v.encounter.open=false;v.encounter.el.hidden=true;v.s.scene='alexandria';v.s.alexandria=normalizeAlexandria(v.s.alexandria);v.s.completed=true;v.s.items=v.s.items.filter(id=>id!=='ticket');if(this.a.stage>=5&&!v.s.items.includes('mary-parcel'))v.s.items.push('mary-parcel');this.el.hidden=false;v.keys.clear();v.target=null;this.approach=null;this.prepareApproach();this.save();this.ui();v.sound.request('malta');
 if(!this.loading){this.loading=Promise.all(['street','lobby','shop','dining','room','owner','mary','alpedrinha','alpedrinha-walk','dinner-together','room-dress-v1'].map(async id=>{const im=new Image();im.src=`assets/alexandria-study/${id==='room'?'room-door':id==='lobby'?'lobby-door':id}.png`;await im.decode();this.images[id]=im;})).then(()=>{this.ready=true;v.q('.voyage-loading').hidden=true;this.maybeArrival();this.ui();this.paint();}).catch(()=>{v.q('.voyage-loading').innerHTML='街景未能载入。请刷新重试。';});}await this.loading;this.maybeArrival();}
 blocked(){return !this.ready||this.v.paused||!!this.fade||!!this.approach||this.bagOpen||!!this.menu||!!this.a.dialogue&&!this.suspended||['interlude','outbound'].includes(this.a.room);}
 stop(){this.v.keys.clear();this.v.target=null;this.v.moving=false;}
 go(room,x,label=place[room],from={...this.a}){this.stop();this.menu=null;this.fade={t:0,room,x,label,swapped:false,from};this.ui();}
 maybeArrival(){const a=this.a;if(this.ready&&this.v.active&&!this.v.paused&&!this.fade&&!this.bagOpen&&!this.menu&&!a.arrivalSeen&&a.stage===0&&a.room==='street'&&!a.dialogue){a.arrivalSeen=true;this.talk('port');}}
 prepareApproach(){const a=this.a;if(a.room==='lobby'&&a.dialogue==='register'&&a.index>=3&&!a.porterArrived&&!this.suspended)this.approach={to:Math.max(100,a.x-82)};}
 talk(id){if(this.v.paused||this.fade||this.approach||this.bagOpen||this.menu||!this.ready)return;this.stop();if(this.a.dialogue!==id){this.a.dialogue=id;this.a.index=0;}this.suspended=false;this.prepareApproach();this.save();this.ui();}
 close(){if(this.v.paused||this.approach)return;if(this.menu)this.menu=null;else this.suspended=true;this.stop();this.ui();this.v.el.focus({preventScroll:true});}
 next(){if(this.v.paused||this.fade||this.approach||!this.ready)return;const a=this.a;
 if(a.room==='outbound'){this.save();try{localStorage.setItem('reliquia.jerusalem-study.settings',JSON.stringify(this.v.prefs));}catch{}this.v.sound.stop();(window.top.__reliquiaCover?.entered?window.top.__reliquiaCover.navigate:destination=>window.location.assign(destination))(chapterEntryURL('./jerusalem-study.html?from=alexandria'+(new URLSearchParams(location.search).has('preview')?'&preview=1':'')));return;}
 if(a.room==='interlude'){a.index++;if(a.index>=interlude.length){a.index=0;this.go('room',450,'离别的清晨');}this.save();this.ui();return;}
 if(this.menu){const row=this.menu.rows[this.selected];row?.run();return;}
 if(!a.dialogue||this.suspended)return;const d=dialogue[a.dialogue];if(++a.index<d.rows.length){this.prepareApproach();this.save();this.ui();return;}
 if(['scholarBefore','scholar'].includes(a.dialogue))a.scholarHeard=[...new Set([...(a.scholarHeard||[]),a.dialogue])];
 const porterTopic=porterTopics.some(([id])=>id===a.dialogue);const event=d.event,completedScene={...a};a.dialogue=null;a.index=0;
 if(event){const from=completedScene,before=a.stage,next=alexAction(a,event);this.v.s.alexandria=next;
 if(next.stage!==before){if(event==='gift'){if(!this.v.s.items.includes('mary-parcel'))this.v.s.items.push('mary-parcel');next.parcelNotice=true;this.v.sound.good();}if(event==='dinner'){next.index=0;this.go('interlude',450,'',from);}if(event==='meet'){this.talk('invite');return;}if(event==='goodbye')this.go('street',150,'亚历山德里亚 · 码头',from);}}
 if(porterTopic){a.porterAsked=[...new Set([...(a.porterAsked||[]),completedScene.dialogue])];this.porterMenu();}this.save();this.ui();this.v.el.focus({preventScroll:true});}
 porterMenu(){this.options('与阿尔佩德里尼亚交谈',(porterTopics.some(([id])=>!(this.a.porterAsked||[]).includes(id))?porterTopics.filter(([id])=>!(this.a.porterAsked||[]).includes(id)):porterTopics).map(([id,label])=>({label,run:()=>{this.menu=null;this.talk(id);}})));}
 options(title,rows){this.stop();this.menu={title,rows:[...rows,{label:'返回',run:()=>{this.menu=null;this.ui();}}]};this.selected=0;this.ui();}
 interact(id){if(this.blocked())return;const p=id?this.spots().find(x=>x.id===id):this.nearest();if(!p)return;if(Math.abs(p.x-this.a.x)>95){const person=['owner','porter','maryShop','maryDinner','maryRoom'].includes(p.id);this.v.target={x:p.x+(person?(this.a.x<p.x?-78:78):0),id:p.id};return;}
 const a=this.a;
 if(p.inspect)return this.talk(inspectionDialogue(p.id,a.stage));
 if(p.id==='porter')return this.porterMenu();
 if(p.id==='hotel')return this.go('lobby',170);
 if(p.id==='shopDoor'){if(a.stage<1)return this.talk('port');return this.go('shop',175);}
 if(p.id==='chapel')return this.talk(a.stage<2?'churchBefore':'church');
 if(p.id==='port'){if(a.stage===6)return this.options('登船离开',[{label:'乘凯芒号前往雅法',run:()=>{this.v.s.alexandria=alexAction(a,'depart');this.save();this.go('outbound',150,'驶向雅法',{...a});this.v.sound.ship();}}]);return this.talk(a.stage===0?'port':'earlyLeave');}
 if(p.id==='exit')return this.go(a.room==='lobby'?'street':'lobby',a.room==='lobby'?780:900);
 if(p.id==='shopExit')return this.go('street',1410);
 if(p.id==='interiorDoor'&&a.stage===0)return this.talk('checkInFirst');
 if(p.id==='owner'||p.id==='interiorDoor'){if(a.stage===0)return this.talk('register');return this.options(p.id==='interiorDoor'?'前往':'您要去哪里？',[{label:'餐厅',run:()=>this.go('dining',180)},{label:'客房',run:()=>this.go('room',450)}]);}
 if(p.id==='maryShop'){if(a.stage===1)return this.talk('meet');if(a.stage===2)return this.options('玛丽望着我',[{label:'邀她共进晚餐',run:()=>{this.menu=null;this.talk('invite');}}]);return this.talk('maryWait');}
 if(p.id==='maryDinner')return this.talk('dinner');
 if(p.id==='nightdress'){a.x=758;a.facing=-1;return this.talk('gift');}
 if(p.id==='maryRoom')return this.talk(a.stage===4?'gift':'goodbye');
 }
 spots(){return [...this.mainSpots(),...inspectionSpots(this.a)];}
 mainSpots(){const a=this.a;if(a.room==='street')return [{id:'port',x:150,y:385,label:a.stage===6?'登船离开':'查看码头'},{id:'hotel',x:780,y:395,label:'进入酒店'},{id:'shopDoor',x:1410,y:395,label:'进入小店'},{id:'chapel',x:1840,y:395,label:'看看教堂'}];if(a.room==='lobby')return [{id:'exit',x:160,y:420,label:'返回主街'},...(a.stage>=1?[{id:'porter',x:a.porterX,y:305,label:'与同乡交谈'}]:[]),{id:'owner',x:755,markerX:785,y:251,label:a.stage===0?'登记入住':'选择去向'},{id:'interiorDoor',x:905,y:305,label:a.stage===0?'询问客房':'选择去向'}];if(a.room==='shop')return [{id:'shopExit',x:170,y:420,label:'返回主街'},...(a.stage<4?[{id:'maryShop',x:515,y:305,label:'与玛丽交谈'}]:[])];if(a.room==='dining')return [{id:'exit',x:160,y:420,label:'返回门厅'},...(a.stage===3?[{id:'maryDinner',x:685,y:322,label:'共进晚餐'}]:[])];if(a.room==='room')return [...(![4,5].includes(a.stage)?[{id:'exit',x:890,y:415,label:'返回门厅'}]:[]),...(a.stage===4?[{id:'nightdress',x:680,y:340,label:'查看睡衣'}]:a.stage===5?[{id:'maryRoom',x:590,y:322,label:'向玛丽告别'}]:[])];return [];}
 nearest(){return this.spots().filter(p=>Math.abs(p.x-this.a.x)<95).sort((a,b)=>Math.abs(a.x-this.a.x)-Math.abs(b.x-this.a.x))[0];}
 bag(){if(this.v.paused||this.fade||this.approach||this.menu||this.a.dialogue&&!this.suspended||!this.ready||this.a.room==='interlude')return;this.stop();this.bagOpen=!this.bagOpen;if(this.bagOpen){this.a.parcelNotice=false;this.save();this.v.backpack.open(this.v.s.items,{checked:true});}else{this.v.backpack.close();this.v.el.focus({preventScroll:true});}this.ui();}
 key(e){const code=e.code;if(this.v.paused||e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,summary'))return;if(this.bagOpen){this.v.backpack.key(e);return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyS','KeyA','KeyD','KeyE','Space','Enter','Escape','Tab','KeyR'].includes(code)){e.preventDefault();e.stopImmediatePropagation();}if(e.repeat&&['KeyE','Space','Enter','Escape','Tab','KeyR'].includes(code))return;
 if(code==='Escape'){if(this.approach){this.v.onMenu();return;}if(this.menu||this.a.dialogue&&!this.suspended)this.close();else this.v.onMenu();return;}if(this.fade||!this.ready)return;
 if(code==='Tab'){this.bag();return;}if(this.menu&&['KeyW','KeyS'].includes(code)){this.selected=(this.selected+(code==='KeyS'?1:-1)+this.menu.rows.length)%this.menu.rows.length;this.ui();return;}
 if(code==='Space'){if(this.menu||this.a.dialogue&&!this.suspended||['interlude','outbound'].includes(this.a.room))this.next();return;}
 if(code==='KeyE'){if(!this.blocked())this.interact();return;}if(code==='Enter')return;
 if(code==='KeyR'&&!this.blocked()){this.talk(this.a.stage<2?'scholarBefore':'scholar');return;}if(this.blocked())return;if(['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(code)){this.v.keys.add(code);this.v.target=null;}}
 pointer(e){if(this.blocked())return;const r=this.v.canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*960+this.camera;const p=this.spots().filter(p=>Math.abs(p.x-x)<60).sort((a,b)=>Math.abs(a.x-x)-Math.abs(b.x-x))[0];if(p){this.interact(p.id);return;}this.v.target={x:Math.max(55,Math.min(this.a.room==='street'?2110:905,x))};}
 ui(){if(!this.a)return;const v=this.v,a=this.a;this.el.hidden=false;v.el.dataset.scene='alexandria';v.canvas.setAttribute('aria-label',place[a.room]);v.el.dataset.transition=this.fade?'alex':'';v.q('.voyage-title').hidden=true;v.q('.voyage-hud').hidden=false;v.q('.voyage-place').textContent=place[a.room];v.q('.voyage-dialogue').hidden=true;v.q('.voyage-teaching').hidden=true;v.q('.voyage-next-port').hidden=true;v.q('.malta-departure-hint').hidden=true;v.q('.voyage-iris').style.opacity=0;v.encounter.el.hidden=true;v.q('.voyage-loading').hidden=this.ready;v.q('.voyage-bag').hidden=!this.bagOpen;
 if(a.dialogue&&!dialogue[a.dialogue]){a.dialogue=null;a.index=0;}
 this.q('.alex-portrait').classList.toggle('scholar-pending',!(a.scholarHeard||[]).includes(a.stage<2?'scholarBefore':'scholar'));
 const active=!!a.dialogue&&!this.suspended&&!this.approach;this.q('.alex-parcel-notice').hidden=!a.parcelNotice||this.bagOpen||active||!!this.fade||!!this.menu;this.q('.alex-talk').hidden=!active;this.q('.alex-menu').hidden=!this.menu;this.q('.alex-portrait').hidden=['interlude','outbound'].includes(a.room);this.q('.alex-portrait').disabled=active||!!this.menu||!!this.fade||!!this.approach||this.bagOpen;
 if(active){const rows=dialogue[a.dialogue].rows,row=rows[Math.min(a.index,rows.length-1)];const thought=isThought(a.dialogue,a.index),interjection=isInterjection(a.dialogue,a.index);this.q('.alex-talk').classList.toggle('is-interjection',interjection);this.q('.alex-talk').classList.toggle('is-scholar',row[0]==='托普修斯');this.q('.alex-talk').classList.toggle('is-thought',thought);this.q('.alex-talk').setAttribute('aria-label',thought?'特奥多里科的心声':isInspection(a.dialogue)?'物件内容':'交谈');this.q('.alex-talk small').textContent=thought?'特奥多里科 · 心声':isInspection(a.dialogue)?'':row[0];this.q('.alex-talk p').textContent=a.dialogue==='earlyLeave'?earlyLeaveText(a.stage):row[1];this.q('[data-next]').innerHTML=(a.index===rows.length-1?'继续':'继续')+' <kbd aria-label="空格键">␣</kbd>';}
 const paper=active&&(a.dialogue==='shopCard'||a.dialogue==='gift'&&a.index===3);this.q('.alex-stationery').hidden=!paper;this.q('.alex-stationery').innerHTML=paper?maryPaper(a.dialogue==='shopCard'?'shop':'dedication'):'';this.q('.alex-talk > p').hidden=paper&&a.dialogue==='gift';
 const prices=active&&['restaurantMenu','restaurantMenuMary'].includes(a.dialogue)&&a.index===0;this.q('.alex-price-list').hidden=!prices;this.q('.alex-price-list').innerHTML=prices?menuPrices:'';
 if(this.menu){this.q('.alex-menu h2').textContent=this.menu.title;const box=this.q('.alex-menu div');box.replaceChildren();this.menu.rows.forEach((row,i)=>{const b=document.createElement('button');b.textContent=row.label;b.classList.toggle('selected',i===this.selected);b.onclick=()=>{if(v.paused)return;this.selected=i;row.run();};box.append(b);});}
 const box=v.q('.voyage-markers');box.replaceChildren();for(const p of this.spots()){const b=document.createElement('button');b.className='voyage-spot';b.dataset.spot=p.id;setPixelPrompt(b,p.label);b.onclick=()=>this.interact(p.id);box.append(b);}v.q('.voyage-hud').inert=active||!!this.menu||!!this.fade;v.q('.voyage-markers').inert=false;v.canvas.style.pointerEvents='';this.position();this.black();}
 position(){this.camera=this.a.room==='street'?Math.max(0,Math.min(1200,this.a.x-420)):0;const p=this.nearest();for(const b of this.v.q('.voyage-markers').children){const s=this.spots().find(p=>p.id===b.dataset.spot);b.style.left=(((s.markerX??s.x)-this.camera)/960*100)+'%';let y=s.y;const x=s.markerX??s.x;const faces=this.a.room==='lobby'?[{x:785,y:274},{x:this.a.porterX,y:320}]:this.a.room==='shop'&&this.a.stage<4?[{x:520,y:320}]:this.a.room==='dining'&&this.a.stage===3?[{x:690,y:344}]:this.a.room==='room'&&[4,5].includes(this.a.stage)?[{x:590,y:344}]:[];for(const f of faces)if(Math.abs(x-f.x)<75)y=Math.min(y,f.y-18);const feet=this.a.room==='street'?478:['dining','room'].includes(this.a.room)?500:476;if(Math.abs(x-this.a.x)<70)y=Math.min(y,feet-174);b.style.top=(y/540*100)+'%';b.hidden=this.blocked()||p?.id!==s.id;}}
 black(){const b=this.q('.alex-black'),a=this.a;const opaque=['interlude','outbound'].includes(a.room);b.hidden=this.bagOpen||!this.fade&&!opaque;if(this.fade){const t=this.fade.t;b.style.opacity=t<.45?t/.45:t<1.5?1:Math.max(0,1-(t-1.5)/.5);this.q('.alex-black p').textContent=t>=.45&&t<1.5?this.fade.label:'';this.q('[data-black]').hidden=true;}else{b.style.opacity=1;this.q('.alex-black p').textContent=a.room==='interlude'?interlude[Math.min(a.index,1)]:'我带着玛丽的包裹，乘凯芒号驶向雅法。耶路撒冷，在前面等着我。';this.q('[data-black]').hidden=!opaque;this.q('[data-black]').innerHTML=a.room==='outbound'?'继续前往耶路撒冷 <kbd aria-label="空格键">␣</kbd>':'继续 <kbd aria-label="空格键">␣</kbd>';}b.classList.toggle('alex-ending',a.room==='outbound'&&!this.fade);}
 tick(dt){if(!this.ready||this.v.paused)return;const a=this.a,v=this.v;v.time+=dt/1000;if(!a.arrivalSeen)this.maybeArrival();
 if(this.approach){const dist=this.approach.to-a.porterX,step=Math.min(Math.abs(dist),105*dt/1000);a.porterX+=Math.sign(dist)*step;this.porterDistance+=step;v.moving=false;if(Math.abs(this.approach.to-a.porterX)<1){a.porterArrived=true;a.facing=-1;this.approach=null;this.save();this.ui();}}
 else if(this.fade){this.fade.t+=dt/1000;if(this.fade.t>=.85&&!this.fade.swapped){this.fade.swapped=true;a.room=this.fade.room;a.x=this.fade.x;a.facing=1;this.save();this.ui();}if(this.fade.t>=2){this.fade=null;this.maybeArrival();this.ui();}}
 else if(!this.blocked()){let dir=(v.keys.has('ArrowRight')||v.keys.has('KeyD')?1:0)-(v.keys.has('ArrowLeft')||v.keys.has('KeyA')?1:0);if(v.target){const dist=v.target.x-a.x;if(Math.abs(dist)<5){const id=v.target.id;v.target=null;if(id)this.interact(id);}else dir=Math.sign(dist);}const old=a.x,step=210*dt/1000,delta=dir*(v.target?Math.min(step,Math.abs(v.target.x-a.x)):step);a.x=Math.max(55,Math.min(a.room==='street'?2110:905,a.x+delta));v.moving=a.x!==old;if(v.moving){a.facing=dir;this.distance+=Math.abs(a.x-old);if(v.time-this.lastSave>.5){this.save();this.lastSave=v.time;}}}else v.moving=false;
 this.position();this.paint();this.black();}
 drawPorter(x){if(!this.approach){this.npc('alpedrinha',x);return;}const c=this.v.ctx,frame=Math.floor(this.porterDistance/12)%6;c.drawImage(this.images['alpedrinha-walk'],frame*64,0,64,80,Math.round(x-64),316,128,160);}
 npc(id,x,feet=476){const im=this.images[id],h=SCROLL_SCALE.adultHeight,w=im.width/im.height*h;this.v.ctx.drawImage(im,x-w/2,feet-h,w,h);}
 paint(){if(!this.ready)return;const c=this.v.ctx,a=this.fade&&!this.fade.swapped?this.fade.from:this.a;c.imageSmoothingEnabled=false;c.clearRect(0,0,960,540);if(['interlude','outbound'].includes(a.room)){c.fillStyle='#050810';c.fillRect(0,0,960,540);return;}if(a.room==='street'){c.drawImage(this.images.street,-this.camera,-160,2160,720);drawStreetSigns(c,this.camera);}else c.drawImage(this.images[a.room==='room'&&a.stage===4?'room-dress-v1':a.room],0,0,960,540);
 if(a.room==='dining')drawMenu(c);
 if(a.room==='shop')drawShopCard(c);
 if(a.room==='dining'&&a.dialogue==='dinner'&&!this.suspended){c.drawImage(this.images['dinner-together'],0,0,960,540);return;}
 if(a.room==='lobby'){this.npc('owner',785,430);c.drawImage(this.images.lobby,274,190,144,38,548,380,288,76);drawLedger(c);this.drawPorter(a.porterX);}
 if(a.room==='shop'&&a.stage<4)this.npc('mary',520);
 if(a.room==='dining'&&a.stage===3)this.npc('mary',690,500);
 if(a.room==='room'&&[4,5].includes(a.stage)){this.npc('mary',590,500);}
 const feet=a.room==='street'?478:['dining','room'].includes(a.room)?500:476;drawActor(c,this.v.moving?this.v.assets.teo:this.v.assets.teoIdle,this.v.moving?'teo':'teoIdle',{x:a.x-this.camera,feet,facing:a.facing,frame:this.v.moving?walkFrame(this.distance):0});}
}
