import {porterTopics} from './content.js';
export const initialAlexandria=()=>({room:'street',x:150,facing:1,stage:0,dialogue:null,index:0,scriptVersion:4,porterX:515,porterArrived:false,porterAsked:[],parcelNotice:false,arrivalSeen:false});
const rooms=['street','lobby','shop','dining','room','interlude','outbound'];
export function normalizeAlexandria(value){const a={...initialAlexandria(),...value};a.stage=Number.isInteger(a.stage)?Math.max(0,Math.min(7,a.stage)):0;if(!rooms.includes(a.room))a.room='street';if(a.stage<1&&['dining','room','shop'].includes(a.room))a.room='street';if(a.stage===4&&a.room==='interlude'){}else if(a.room==='interlude')a.room='street';if(a.room==='outbound'&&a.stage<7)a.room='street';a.x=Number.isFinite(a.x)?Math.max(55,Math.min(a.room==='street'?2110:905,a.x)):150;a.facing=a.facing===-1?-1:1;a.dialogue=typeof a.dialogue==='string'?a.dialogue:null;a.index=Number.isInteger(a.index)?Math.max(0,a.index):0;if((value?.scriptVersion??1)<2&&a.dialogue==='register'&&a.index>=3)a.index--;if((value?.scriptVersion??1)<3&&a.dialogue==='gift')a.index=[0,0,1,2,3,4,4][Math.min(a.index,6)];if(a.dialogue==='restaurantMenuMary'&&a.stage<3)a.dialogue='restaurantMenu';if((value?.scriptVersion??1)<4&&a.dialogue==='register')a.index=[0,1,2,3,4,4,4,4,5,6][Math.min(a.index,9)];if((value?.scriptVersion??1)<4&&a.dialogue==='scholar'){a.dialogue=a.stage<2?'scholarBefore':'scholar';a.index=0;}a.scriptVersion=4;a.porterX=Number.isFinite(a.porterX)?Math.max(55,Math.min(850,a.porterX)):515;a.porterArrived=!!a.porterArrived;a.porterAsked=[...new Set((Array.isArray(a.porterAsked)?a.porterAsked:[]).filter(id=>porterTopics.some(([topic])=>topic===id)))];a.parcelNotice=!!a.parcelNotice;a.arrivalSeen=typeof value?.arrivalSeen==='boolean'?value.arrivalSeen:a.stage>0||a.room!=='street'||a.x>240;return a;}
export function alexAction(a,event){
 const expected={register:0,meet:1,invite:2,dinner:3,gift:4,goodbye:5,depart:6};
 if(a.stage!==expected[event])return a;
 const stage=a.stage+1;
 return {...a,stage,dialogue:null,index:0,...(event==='dinner'?{room:'interlude'}:event==='goodbye'?{room:'street',x:150}:event==='depart'?{room:'outbound',x:150}:{})};
}
