import {drawStreetSigns} from './signs.js';
import {SCROLL_SCALE,drawActor} from '../voyage/scale.js';
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');
const entries={street:['亚历山德里亚 · 主街与码头','从码头抵达，经过酒店与玛丽的小店，走到树荫下的教堂。街景布局为剧情改编。','我就在这里上岸，开始了在亚历山德里亚的日子。'],lobby:['酒店门厅','登记簿、墨水与行李，留下同乡相认的位置。','我抢过笔，写下了我的名字和祖国。'],shop:['玛丽的小店','紫色木手、手套、蜡花与白猫；柜台前保留交谈空间。','我是阿尔佩德里尼亚介绍来的。'],dining:['酒店餐厅','暗红桌布、两只酒杯与暖灯；正式就餐姿势将在美术确认后制作。','只要她肯对我笑，我便乐意付这香槟的钱。'],room:['告别客房','床、书桌和收拾中的行李；在这里，我收到她的纪念物。','我把她的包裹紧紧夹在胳膊下，舍不得松开。'],malta:['马耳他 · 尺度对照','复用第三章第二节背景与人物尺寸。',''],deck:['马拉加号 · 尺度对照','复用第三章第一节甲板与人物尺寸。','']};
let current='street';const images={};
const paths={street:'alexandria-study/street.png',owner:'alexandria-study/owner.png',lobby:'alexandria-study/lobby.png',shop:'alexandria-study/shop.png',dining:'alexandria-study/dining.png',room:'alexandria-study/room-door.png',mary:'alexandria-study/mary.png',alpedrinha:'alexandria-study/alpedrinha.png',parcel:'alexandria-study/parcel.png',teo:'voyage/teodorico-idle.png',malta:'malta/malta.webp',deck:'voyage/deck-clear.webp'};
await Promise.all(Object.entries(paths).map(async([id,path])=>{const im=new Image();im.src='./assets/'+path;await im.decode();images[id]=im;}));
function actor(id,x,feet=476){const im=images[id];if(id==='teo')drawActor(ctx,im,'teoIdle',{x,feet});else ctx.drawImage(im,Math.round(x-im.width/im.height*SCROLL_SCALE.adultHeight/2),feet-SCROLL_SCALE.adultHeight,im.width/im.height*SCROLL_SCALE.adultHeight,SCROLL_SCALE.adultHeight);}
function paint(){ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,960,540);if(current==='street'){const camera=Number(document.querySelector('#street-pan').value);ctx.drawImage(images.street,-camera,-160,2160,720);drawStreetSigns(ctx,camera);}else if(current==='deck')ctx.drawImage(images.deck,0,SCROLL_SCALE.worldTop+SCROLL_SCALE.deckOffset,1280,720);else ctx.drawImage(images[current],0,0,960,540);
if(document.querySelector('#actors').checked){if(current==='street'){actor('teo',350,478);}else if(current==='lobby'){actor('teo',410);actor('alpedrinha',510);actor('owner',785,430);ctx.drawImage(images.lobby,274,190,144,38,548,380,288,76);}else if(current==='shop'){actor('teo',350);actor('mary',500);}else if(current==='dining'){actor('teo',340,500);actor('mary',710,500);}else if(current==='room'){actor('teo',455,500);actor('mary',590,500);}else actor('teo',350,496);}
if(document.querySelector('#words').checked&&entries[current][2]){ctx.fillStyle='rgba(8,17,26,.92)';ctx.fillRect(195,74,570,74);ctx.strokeStyle='#ae8950';ctx.strokeRect(195,74,570,74);ctx.fillStyle='#f3e3bd';ctx.font='21px "Songti SC",serif';ctx.textAlign='center';ctx.fillText(entries[current][2],480,117,530);}
document.querySelector('#street-controls').hidden=current!=='street';canvas.setAttribute('aria-label',entries[current][0]+'美术预览');document.querySelector('#caption').textContent=entries[current][1];}
document.querySelectorAll('[data-scene]').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.scene;document.querySelectorAll('[data-scene]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));paint();}));document.querySelector('#street-pan').addEventListener('input',paint);document.querySelectorAll('input').forEach(el=>el.addEventListener('change',paint));paint();
