import {cards,groups} from './content.js';
export const phases=['arrival','inspection','awaken','challenge','battle','cast','triumphHold','triumph','homeFade','eveningBlack','chapelFade','evening','seat','seating','lights','lampRequest','lighting','ceremony','silence','congratulate','unbox','perfume','revealHold','recognize','cardInspect','inscription','shock','accusations','curtainClosing','curtainClosed','curtainOpening','empty','roomFade','roomBlack','roomIn','dismissal','take','leaving','exit','outside','ending','end'];
export const initial=()=>({version:1,phase:'arrival',line:0,used:[],pending:null,step:0,unwrap:0,unwrapDX:0,unwrapDY:0,elapsed:0,items:['c5-small-crate','c5-relic-box'],carried:false,complete:false,volume:.65,muted:false,reduced:false});
export function normalize(raw={}){const s={...initial(),...raw,version:1};if(!phases.includes(s.phase))s.phase='arrival';s.used=[...new Set((Array.isArray(s.used)?s.used:[]).filter(id=>cards.some(c=>c.id===id)))];s.pending=cards.some(c=>c.id===s.pending)?s.pending:null;s.line=Math.max(0,Math.min(groups[s.phase]?.length-1||0,Number(s.line)||0));s.step=Math.max(0,Math.min(7,Math.floor(Number(s.step)||0)));s.unwrap=Math.max(0,Math.min(1,Number(s.unwrap)||0));for(const k of ['unwrapDX','unwrapDY'])s[k]=Math.max(-1,Math.min(1,Number(s[k])||0));s.elapsed=Math.max(0,Number(s.elapsed)||0);s.volume=Math.max(0,Math.min(1,Number(s.volume)||0));s.items=Array.isArray(s.items)?[...new Set(s.items)]:initial().items;if(!s.items.includes('c5-small-crate'))s.items.push('c5-small-crate');if(s.phase==='cast'&&!s.pending)s.phase=s.used.length===3?'triumphHold':'battle';if(s.phase==='battle'&&s.used.length===3)s.phase='triumphHold';if(s.complete||s.carried)s.items=s.items.filter(i=>i!=='c5-relic-box'&&i!=='c5-returned-parcel'&&i!=='mary-parcel'&&i!=='thorn-parcel');return s;}
export function goto(s,phase,extra={}){return normalize({...s,phase,line:0,elapsed:0,...extra});}
export function selectCard(s,id){if(s.phase!=='battle'||s.used.includes(id)||!cards.some(c=>c.id===id))return s;return goto(s,'cast',{pending:id});}
export function finishCast(s){if(s.phase!=='cast'||!s.pending)return s;const used=[...new Set([...s.used,s.pending])];return goto(s,used.length===3?'triumphHold':'battle',{used,pending:null});}
const after={arrival:'inspection',inspection:'awaken',challenge:'battle',triumph:'homeFade',eveningBlack:'chapelFade',evening:'seating',seating:'seat',lampRequest:'lighting',lighting:'ceremony',ceremony:'silence',congratulate:'unbox',perfume:'unbox',recognize:'cardInspect',accusations:'curtainClosing',dismissal:'take',leaving:'exit',outside:'ending'};
export function nextLine(s){const rows=groups[s.phase];if(!rows)return s;if(s.line<rows.length-1)return {...s,line:s.line+1};return goto(s,after[s.phase]||s.phase,s.phase==='perfume'?{step:2,unwrap:0}:{});}
export function action(s){if(s.phase==='seat')return goto(s,'lights');if(s.phase==='lights')return goto(s,'lampRequest');if(s.phase==='unbox'){if(s.unwrap<1)return s;const step=s.step+1;if(step===2)return goto(s,'perfume',{step,unwrap:0,unwrapDX:0,unwrapDY:0});if(step===7)return goto(s,'revealHold',{step,unwrap:0,unwrapDX:0,unwrapDY:0});return {...s,step,unwrap:0,unwrapDX:0,unwrapDY:0,elapsed:0};}if(s.phase==='cardInspect')return goto(s,'inscription');if(s.phase==='inscription')return goto(s,'shock');if(s.phase==='curtainClosed')return goto(s,'curtainOpening');if(s.phase==='empty')return goto(s,'roomFade');if(s.phase==='take')return goto(s,'leaving',{carried:true});if(s.phase==='exit')return goto(s,'outside');return s;}
export const durations={homeFade:1.6,chapelFade:1.8,roomFade:1.4,roomBlack:.8,roomIn:1.6,awaken:1,cast:4.4,triumphHold:3.5,lighting:3.2,silence:1.6,revealHold:2,shock:2.5,curtainClosing:1.8,curtainOpening:2.2,ending:2};
export function tick(s,dt){if(!durations[s.phase])return s;const elapsed=s.elapsed+dt;if(elapsed<durations[s.phase])return {...s,elapsed};if(s.phase==='cast')return finishCast(s);const next={homeFade:'eveningBlack',chapelFade:'seating',roomFade:'roomBlack',roomBlack:'roomIn',roomIn:'dismissal',awaken:'challenge',triumphHold:'triumph',lighting:'ceremony',silence:'congratulate',revealHold:'recognize',shock:'accusations',curtainClosing:'curtainClosed',curtainOpening:'empty',ending:'end'}[s.phase];return goto(s,next,next==='end'?{complete:true}:{});}
export function area(s){if(s.phase==='arrival'&&s.line===5)return 'bedroom';if(['arrival','outside','ending','end'].includes(s.phase))return 'door';if(['inspection','awaken','challenge','battle','cast','triumphHold','triumph','homeFade','eveningBlack','roomIn','dismissal','take','leaving','exit'].includes(s.phase))return 'bedroom';return 'chapel';}
export function mood(s){if(['revealHold','recognize','cardInspect','inscription','shock','accusations','curtainClosing','curtainClosed','curtainOpening','empty','roomFade','roomBlack','roomIn','dismissal','take','leaving','exit','outside','ending','end'].includes(s.phase))return 'angry';if(['inspection','awaken','challenge'].includes(s.phase))return 'stern';if(['battle','cast'].includes(s.phase))return s.used.length>0?'soft':'stern';return 'soft';}
export function chapterScene(s){return area(s)+(phases.indexOf(s.phase)>=phases.indexOf('roomIn')?'-exit':'');}
