// Original procedural sound design: no intelligible dialogue or historical recording.
export class Sound{
 constructor(){this.ctx=null;this.nodes=[];this.silent=true;this.pending=null;}
 async start(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();const c=this.ctx;this.gain=c.createGain();this.gain.gain.value=0;this.gain.connect(c.destination);this.pending=this.loadAmbient();}await this.pending;await this.ctx.resume();}
 async loadAmbient(){const c=this.ctx;try{const response=await fetch('./assets/dream-trial/courtyard.wav');if(!response.ok)throw Error('ambient unavailable');const buffer=await c.decodeAudioData(await response.arrayBuffer());const source=c.createBufferSource();source.buffer=buffer;source.loop=true;this.ambientGain=c.createGain();this.ambientGain.gain.value=10;source.connect(this.ambientGain);this.ambientGain.connect(this.gain);source.start();this.nodes.push(source);}catch(e){console.warn('场景环境声未载入',e);}}
 set({muted,volume},paused=false,talking=false){this.silent=muted||paused||document.hidden;if(this.ctx)this.gain.gain.setTargetAtTime(this.silent?0:volume*(talking?.85:1),this.ctx.currentTime,.2);}
 cue(kind){if(!this.ctx||this.silent)return;const c=this.ctx;const count=kind==='steps'?2:kind==='coins'?3:1;for(let i=0;i<count;i++){const t=c.currentTime+i*(kind==='steps'?.38:.12),g=c.createGain();g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(kind==='steps'?.13:.09,t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+(kind==='bell'?.8:.28));g.connect(this.gain);
 if(kind==='steps'||kind==='work'){const b=c.createBuffer(1,c.sampleRate*.3,c.sampleRate),a=b.getChannelData(0);for(let j=0;j<a.length;j++)a[j]=(Math.random()*2-1)*Math.exp(-j/(c.sampleRate*.035));const n=c.createBufferSource(),f=c.createBiquadFilter();f.type='lowpass';f.frequency.value=kind==='work'?2100:750;n.buffer=b;n.connect(f);f.connect(g);n.start(t);n.stop(t+.3);}else{for(const ratio of [1,2.71,4.13]){const o=c.createOscillator();o.frequency.value=(kind==='coins'?1800+i*130:1100)*ratio;o.connect(g);o.start(t);o.stop(t+.85);}}}}
 close(){this.ctx?.close();}
}
